const flow=window.MICLINE_FLOW,byID=new Map(flow.map(s=>[s.id,s]));let history=[],current='welcome',comparison='processed';
const $=id=>document.getElementById(id),wave='<div class="wave" aria-hidden="true">'+[18,33,48,64,38,56,28,15].map(h=>`<i style="height:${h}px"></i>`).join('')+'</div>';
const choice=(title,sub,select='')=>`<div class="choice"><div><strong>${title}</strong><small>${sub}</small></div>${select}</div>`;
const select=(label,options)=>`<select aria-label="${label}">${options.map(o=>`<option>${o}</option>`).join('')}</select>`;
const meter=(clip=false,silent=false)=>`<div class="meter"><div class="meter-head"><span>${clip?'RAW INPUT · CLIPPED':'RAW INPUT · EXAMPLE'}</span><strong>${silent?'−∞':clip?'+0.2':'−12.3'} <small>dBFS</small></strong></div><div class="track"><div class="fill" style="width:${silent?0:clip?100:78}%"></div><i class="peak" style="left:${silent?0:clip?99:85}%"></i></div><div class="ticks"><span>Quiet</span><span>Room for louder words</span><span>0</span></div><div class="feedback">${silent?'Check the mute switch and selected channel.':clip?'Lower the gain at your microphone.':'Comfortable headroom in this example.'}</div></div>`;
function control(s){switch(s.control){
case'welcome':return '<div class="welcome">'+wave+'<span>Find your level.<br>Shape your sound.<br>Use it anywhere.</span></div>';
case'permission':case'denied':return choice('Microphone access',s.id==='denied'?'Off in macOS Settings':'Requested only when you choose Allow','<span class="symbol">◎</span>');
case'mic':case'silent':return choice('Studio Microphone','Physical input',select('Microphone',['Studio Microphone','Built-in Microphone']))+'<div class="caption-action">'+select('Input channel',['Input 1 · Mono','Input 2 · Mono'])+'</div>';
case'idle':return choice('Ready to listen','Studio Microphone · Input 1','<span class="symbol">◌</span>');
case'meter':return meter()+ '<button class="quiet caption-action" data-go="listen">Stop listening</button>';
case'clipped':return meter(true);
case'position':return '<div class="welcome"><span class="symbol">↔</span><span>Try a little more distance.<br>Keep your voice natural.</span></div>';
case'isolation':return choice('Apple Sound Isolation','Optional · Included with supported macOS','<span class="pill">Voice</span>');
case'headphones':return choice('Headphones only','Confirm the device you are wearing',select('Headphone output',['Studio Headphones','Another headphone output']))+'<p style="font-size:12px;color:#a8b8ac">Preview sends your voice to this device.</p>';
case'compare':case'compression':return choice(s.control==='compare'?'Apple Sound Isolation':'Gentle compression','Listen for clear, natural speech')+'<div class="segmented"><button data-compare="original">Original</button><button data-compare="processed" class="selected">Processed</button></div><button class="quiet caption-action" data-go="audition">Stop preview</button>';
case'compressor':return choice('Gentle compression','Apple AUDynamicsProcessor','<span class="pill">Optional</span>');
case'output':return choice('Processed output','Choose an installed virtual device',select('Output device',['Studio Cable','Another virtual device']))+'<button class="quiet caption-action" data-go="driver">I need a virtual device</button>';
case'handoff':return '<div class="connection"><span>MicLine</span><b>→</b><span>Studio Cable</span><b>→</b><span>Your call app</span></div><button class="quiet caption-action" id="copy-device">Copy device name</button>';
case'verify':case'receiving':return choice('Studio Cable','Look at the input meter in your call app','<span class="pill">Output check</span>')+'<button class="quiet caption-action" data-go="handoff">Stop output check</button>';
case'ready':return choice('Your choices are saved','MicLine stops the output check when you finish.','<span class="symbol">✓</span>');
case'main':return choice('Studio Microphone → Studio Cable','Stopped · Sound check available from Help','<span class="pill">Stopped</span>');
case'driver':return choice('BlackHole','External installer · Other virtual devices work too','<span class="symbol">↗</span>');
case'install':return '<a href="https://existential.audio/blackhole/" target="_blank" rel="noreferrer">Open the official BlackHole site ↗</a><p style="font-size:12px;color:#a8b8ac">Nothing is installed by this prototype.</p>';
case'rescan':return choice('No new device detected','Your microphone setup is saved.','<span class="symbol">↻</span>');
case'restart':return choice('Manual recovery','No service is restarted by MicLine. Follow installer guidance if a restart is required.');
case'disconnected':return choice('Listening stopped','Previous input: Studio Microphone','<span class="symbol">⏸</span>');
case'resume':return choice('Continue your level check','Studio Microphone · No audio running','<span class="symbol">↶</span>');
case'tip':return choice('Gain · 0.0 dB','This tip opens beside Gain in the main window.','<span class="pill">Explain</span>');
case'library':return choice('Installed Audio Units','Use an effect whose behavior you know.');
default:return choice('This step is optional','You can continue without adding an effect.');}}
const transcripts={
'find-isolation':['Open Add Effect in MicLine.','Search for AUSoundIsolation.','The matching Apple Audio Unit appears. This clip stops before adding it.'],
'find-compressor':['Open Add Effect in MicLine.','Search for Dynamics.','AUDynamicsProcessor appears. This clip stops before adding or configuring it.']};
function render(id,remember=true){if(!byID.has(id))id='welcome';if(remember&&current!==id)history.push(current);current=id;const s=byID.get(id);location.hash=id;$('jump').value=id;$('title').textContent=s.title;$('body').textContent=s.body;$('eyebrow').textContent=['Your microphone','Your sound · Optional','Your apps'][s.chapter];document.querySelectorAll('nav span').forEach((n,i)=>n.classList.toggle('active',i===s.chapter));$('control').innerHTML=control(s);$('detail').textContent=s.detail||' ';$('next').textContent=s.primary;$('secondary').textContent=s.secondary?.[0]||'';$('secondary').hidden=!s.secondary;$('back').disabled=!history.length;$('lesson').textContent=s.lesson;
$('media').innerHTML=`<div class="illustration">${wave}<small>Lesson storyboard · capture after implementation</small></div>`;
$('caption').textContent='Final PiP footage will be recorded from the finished app.';$('transcript').replaceChildren();(transcripts[s.clip]||[s.body,'Try the highlighted action at your own pace.','Skip or return later; the lesson is always available from Help.']).forEach(t=>{const li=document.createElement('li');li.textContent=t;$('transcript').append(li)});$('transcript').hidden=true;$('read').textContent='Read the steps';$('branch').hidden=!s.branch;$('branch').textContent=s.branch?.[0]||'';$('extra').hidden=!s.extra;$('extra').textContent=s.extra?.[0]||'';$('title').focus({preventScroll:true});}
flow.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.id+' · '+s.title;$('jump').append(o)});
$('jump').onchange=e=>render(e.target.value);$('next').onclick=()=>render(byID.get(current).next);$('secondary').onclick=()=>render(byID.get(current).secondary[1]);$('branch').onclick=()=>render(byID.get(current).branch[1]);$('extra').onclick=()=>render(byID.get(current).extra[1]);$('end').onclick=()=>render('main');$('back').onclick=()=>render(history.pop()||'welcome',false);$('read').onclick=()=>{$('transcript').hidden=!$('transcript').hidden;$('read').textContent=$('transcript').hidden?'Read the steps':'Hide steps'};
function collapse(){const c=document.querySelector('.companion');c.classList.toggle('collapsed');c.querySelector('video')?.pause();$('hide-video').textContent=c.classList.contains('collapsed')?'+':'−'}$('hide-video').onclick=collapse;$('toggle-companion').onclick=collapse;
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)render(go.dataset.go);const compare=e.target.closest('[data-compare]');if(compare){comparison=compare.dataset.compare;document.querySelectorAll('[data-compare]').forEach(b=>b.classList.toggle('selected',b===compare))}if(e.target.id==='copy-device'){navigator.clipboard?.writeText('Studio Cable').then(()=>e.target.textContent='Copied').catch(()=>e.target.textContent='Studio Cable')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.companion video')?.pause();document.querySelector('.companion').classList.add('collapsed')}});render(location.hash.slice(1)||'welcome',false);
